keys:
  - &primary age1xdxqgt8trmqhg478rjufkfhethkm8sza5km97mzh7tu47pfpcdes9me9kz
  - &host age1vvg7z2xhyzy9c47hhq45efalep32ds0ux69zzpa0kkeuf7rucy7qeqqe4z #SSH-age key
creation_rules:
  - path_regex: .*/secrets/secrets\.yaml$
    key_groups:
      - age:
          - *primary
          - *host